{
    "pets": [
        {
            "_id": "67fc4654998e9806cb58aad6",
            "id": "b06acf17-838f-4cfe-bdb7-6271ae865e95",
            "chance": 0.025,
            "demand": "low",
            "description": "Abyssal Dragon is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the N/A with a 0.025% chance.",
            "eggType": "N/A",
            "image": "/items/abyssal-dragon.png",
            "name": "Abyssal Dragon",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "down",
            "status": "Permanent",
            "updatedAt": "2025-04-18T18:34:45.543Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "abyssal-dragon",
            "value": 80,
            "variants": [
                "Normal",
                "Mythic",
                "ShinyMythic",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 80,
            "stats": {
                "_id": "67fc4656998e9806cb58abd3",
                "petId": "b06acf17-838f-4cfe-bdb7-6271ae865e95",
                "bubbles": 1250,
                "coins": 1700,
                "gems": 20,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa58",
            "id": "cf238310-23d9-454b-b72e-01d57c309eae",
            "chance": 7,
            "demand": "medium",
            "description": "Angel is a Rare pet in Bubble Gum Simulator Infinity. It can be hatched from the Crystal Egg with a 7% chance.",
            "eggType": "Crystal Egg",
            "image": "/items/angel.png",
            "name": "Angel",
            "owners": 0,
            "rarity": "Rare",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.941Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "angel",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ab55",
                "petId": "cf238310-23d9-454b-b72e-01d57c309eae",
                "bubbles": 35,
                "coins": 20,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "6802d61ceabfff64116d4381",
            "id": "78b30fef-08c0-44bf-be6b-c492f6667124",
            "chance": 3,
            "demand": "medium",
            "description": "Angel Bunny is a Epic pet in Bubble Gum Simulator Infinity. It can be hatched from the Bunny Egg with a 3% chance.",
            "eggType": "Bunny Egg",
            "image": "/items/angel-bunny.png",
            "name": "Angel Bunny",
            "owners": 0,
            "rarity": "Epic",
            "trend": "stable",
            "status": "Limited",
            "updatedAt": "2025-04-18T22:48:47.280Z",
            "releasedAt": "2025-04-18T21:00:00.000Z",
            "slug": "angel-bunny",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "6802d6c14654baa6902f69d6",
                "petId": "78b30fef-08c0-44bf-be6b-c492f6667124",
                "__v": 0,
                "bubbles": 95,
                "coins": 105,
                "gems": 0,
                "worldCurrency": {}
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa4c",
            "id": "afaa5ff2-6791-4c01-bebb-55e6842618e0",
            "chance": 100,
            "demand": "medium",
            "description": "Avernus is a Secret pet in Bubble Gum Simulator Infinity. It can be hatched from the N/A with a 100% chance.",
            "eggType": "N/A",
            "image": "/items/avernus.png",
            "name": "Avernus",
            "owners": 0,
            "rarity": "Secret",
            "trend": "down",
            "status": "Limited",
            "updatedAt": "2025-04-18T18:44:01.032Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "avernus",
            "value": 4000,
            "variants": [
                "Normal",
                "Mythic",
                "ShinyMythic",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 4000,
            "stats": {
                "_id": "67fc4656998e9806cb58ab49",
                "petId": "afaa5ff2-6791-4c01-bebb-55e6842618e0",
                "bubbles": 1900,
                "coins": 2600,
                "gems": 35,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aab4",
            "id": "3f00e821-f800-4e1e-9463-1ac44171321f",
            "chance": 5,
            "demand": "medium",
            "description": "Bear is a Rare pet in Bubble Gum Simulator Infinity. It can be hatched from the Common Egg with a 5% chance.",
            "eggType": "Common Egg",
            "image": "/items/bear.png",
            "name": "Bear",
            "owners": 0,
            "rarity": "Rare",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "bear",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58abb1",
                "petId": "3f00e821-f800-4e1e-9463-1ac44171321f",
                "bubbles": 2,
                "coins": 1.5,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa72",
            "id": "0d1c3049-48cc-496d-93b7-67ce780ec20d",
            "chance": 100,
            "demand": "high",
            "description": "Beta TV is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the N/A with a 100% chance.",
            "eggType": "N/A",
            "image": "/items/beta-tv.png",
            "name": "Beta TV",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "up",
            "status": "Limited",
            "updatedAt": "2025-04-15T22:56:12.240Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "beta-tv",
            "value": 325,
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 325,
            "stats": {
                "_id": "67fc4656998e9806cb58ab6f",
                "petId": "0d1c3049-48cc-496d-93b7-67ce780ec20d",
                "bubbles": 110,
                "coins": 95,
                "gems": 1.35,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa4a",
            "id": "5980e3ed-f888-4465-8321-6647a2da615b",
            "chance": 25,
            "demand": "medium",
            "description": "Bunny is a Unique pet in Bubble Gum Simulator Infinity. It can be hatched from the Common Egg with a 25% chance.",
            "eggType": "Common Egg",
            "image": "/items/bunny.png",
            "name": "Bunny",
            "owners": 0,
            "rarity": "Unique",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.941Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "bunny",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ab47",
                "petId": "5980e3ed-f888-4465-8321-6647a2da615b",
                "bubbles": 2,
                "coins": 1.2,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "6802d61ceabfff64116d4373",
            "id": "59f9c85f-a263-46b3-86a0-e94c62d3309b",
            "chance": 64,
            "demand": "medium",
            "description": "Bunny Doggy is a Common pet in Bubble Gum Simulator Infinity. It can be hatched from the Bunny Egg with a 64% chance.",
            "eggType": "Bunny Egg",
            "image": "/items/bunny-doggy.png",
            "name": "Bunny Doggy",
            "owners": 0,
            "rarity": "Common",
            "trend": "stable",
            "status": "Limited",
            "updatedAt": "2025-04-18T22:48:47.280Z",
            "releasedAt": "2025-04-18T21:00:00.000Z",
            "slug": "bunny-doggy",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "6802d6c14654baa6902f69c8",
                "petId": "59f9c85f-a263-46b3-86a0-e94c62d3309b",
                "__v": 0,
                "bubbles": 50,
                "coins": 62,
                "gems": 1.5,
                "worldCurrency": {}
            }
        },
        {
            "_id": "6802d61ceabfff64116d438f",
            "id": "428d8092-6153-40ae-bc1a-f607e1c539bf",
            "chance": 0.0001,
            "demand": "medium",
            "description": "Cardinal Bunny is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the Bunny Egg with a 0.0001% chance.",
            "eggType": "Bunny Egg",
            "image": "/items/cardinal-bunny.png",
            "name": "Cardinal Bunny",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "stable",
            "status": "Limited",
            "updatedAt": "2025-04-18T22:48:47.280Z",
            "releasedAt": "2025-04-18T21:00:00.000Z",
            "slug": "cardinal-bunny",
            "value": "N/A",
            "variants": [
                "Normal",
                "Mythic",
                "ShinyMythic",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "6802d6c14654baa6902f69e4",
                "petId": "428d8092-6153-40ae-bc1a-f607e1c539bf",
                "__v": 0,
                "bubbles": 1425,
                "coins": 2000,
                "gems": 28,
                "worldCurrency": {}
            }
        },
        {
            "_id": "67fc4654998e9806cb58aac4",
            "id": "19d3604c-f9a0-40c5-a3f5-983ddc8549c0",
            "chance": 60,
            "demand": "medium",
            "description": "Cave Bat is a Common pet in Bubble Gum Simulator Infinity. It can be hatched from the Crystal Egg with a 60% chance.",
            "eggType": "Crystal Egg",
            "image": "/items/cave-bat.png",
            "name": "Cave Bat",
            "owners": 0,
            "rarity": "Common",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "cave-bat",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58abc1",
                "petId": "19d3604c-f9a0-40c5-a3f5-983ddc8549c0",
                "bubbles": 14,
                "coins": 9,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "6802d61ceabfff64116d4389",
            "id": "7d75f233-c84f-4be3-9a57-53b8997766ef",
            "chance": 7,
            "demand": "medium",
            "description": "Chubby Bunny is a Rare pet in Bubble Gum Simulator Infinity. It can be hatched from the Pastel Egg with a 7% chance.",
            "eggType": "Pastel Egg",
            "image": "/items/chubby-bunny.png",
            "name": "Chubby Bunny",
            "owners": 0,
            "rarity": "Rare",
            "trend": "stable",
            "status": "Limited",
            "updatedAt": "2025-04-18T22:48:47.280Z",
            "releasedAt": "2025-04-18T21:00:00.000Z",
            "slug": "chubby-bunny",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "6802d6c14654baa6902f69de",
                "petId": "7d75f233-c84f-4be3-9a57-53b8997766ef",
                "__v": 0,
                "bubbles": 100,
                "coins": 115,
                "gems": 0,
                "worldCurrency": {}
            }
        },
        {
            "_id": "67fc4654998e9806cb58aacc",
            "id": "0ab25cd2-8c89-478e-be29-1e4cce9883c7",
            "chance": 100,
            "demand": "medium",
            "description": "Crescent Empress is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the N/A with a 100% chance.",
            "eggType": "N/A",
            "image": "/items/crescent-empress.png",
            "name": "Crescent Empress",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "up",
            "status": "Permanent",
            "updatedAt": "2025-04-18T18:24:49.971Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "crescent-empress",
            "value": 160,
            "variants": [
                "Normal",
                "Mythic",
                "ShinyMythic",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 160,
            "stats": {
                "_id": "67fc4656998e9806cb58abc9",
                "petId": "0ab25cd2-8c89-478e-be29-1e4cce9883c7",
                "bubbles": 1100,
                "coins": 1425,
                "gems": 19,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa62",
            "id": "5493b4d4-9b31-456c-800e-80493592a495",
            "chance": 29.9,
            "demand": "medium",
            "description": "Dark Bat is a Unique pet in Bubble Gum Simulator Infinity. It can be hatched from the Crystal Egg with a 29.9% chance.",
            "eggType": "Crystal Egg",
            "image": "/items/dark-bat.png",
            "name": "Dark Bat",
            "owners": 0,
            "rarity": "Unique",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.941Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "dark-bat",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ab5f",
                "petId": "5493b4d4-9b31-456c-800e-80493592a495",
                "bubbles": 25,
                "coins": 12,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa84",
            "id": "cacabb47-abc0-4780-b967-41943e323baf",
            "chance": 6.5,
            "demand": "medium",
            "description": "Dark Dragon is a Epic pet in Bubble Gum Simulator Infinity. It can be hatched from the Spikey Egg with a 6.5% chance.",
            "eggType": "Spikey Egg",
            "image": "/items/dark-dragon.png",
            "name": "Dark Dragon",
            "owners": 0,
            "rarity": "Epic",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "dark-dragon",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ab81",
                "petId": "cacabb47-abc0-4780-b967-41943e323baf",
                "bubbles": 16,
                "coins": 12,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58ab1c",
            "id": "a1aa75ea-cd4c-4716-af27-9d164cb0e94a",
            "chance": 0.05,
            "demand": "medium",
            "description": "Dark Phoenix is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the Void Egg with a 0.05% chance.",
            "eggType": "Void Egg",
            "image": "/items/dark-phoenix.png",
            "name": "Dark Phoenix",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "dark-phoenix",
            "value": "N/A",
            "variants": [
                "Normal",
                "Mythic",
                "ShinyMythic",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ac19",
                "petId": "a1aa75ea-cd4c-4716-af27-9d164cb0e94a",
                "bubbles": 350,
                "coins": 410,
                "gems": 4.5,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa56",
            "id": "898676c1-0d43-4760-a851-509e38dc551d",
            "chance": 25,
            "demand": "medium",
            "description": "Deer is a Common pet in Bubble Gum Simulator Infinity. It can be hatched from the Iceshard Egg with a 25% chance.",
            "eggType": "Iceshard Egg",
            "image": "/items/deer.png",
            "name": "Deer",
            "owners": 0,
            "rarity": "Common",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.941Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "deer",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ab53",
                "petId": "898676c1-0d43-4760-a851-509e38dc551d",
                "bubbles": 5,
                "coins": 3.5,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa66",
            "id": "ecf45b6f-4f7e-43cf-b702-891316173430",
            "chance": 2.25,
            "demand": "medium",
            "description": "Demon is a Epic pet in Bubble Gum Simulator Infinity. It can be hatched from the Magma Egg with a 2.25% chance.",
            "eggType": "Magma Egg",
            "image": "/items/demon.png",
            "name": "Demon",
            "owners": 0,
            "rarity": "Epic",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.941Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "demon",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ab63",
                "petId": "ecf45b6f-4f7e-43cf-b702-891316173430",
                "bubbles": 25,
                "coins": 20,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58ab08",
            "id": "b302e9f7-08b6-41ae-bafb-1faa87ff5993",
            "chance": 60,
            "demand": "medium",
            "description": "Demon Doggy is a Common pet in Bubble Gum Simulator Infinity. It can be hatched from the Nightmare Egg with a 60% chance.",
            "eggType": "Nightmare Egg",
            "image": "/items/demon-doggy.png",
            "name": "Demon Doggy",
            "owners": 0,
            "rarity": "Common",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "demon-doggy",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ac05",
                "petId": "b302e9f7-08b6-41ae-bafb-1faa87ff5993",
                "bubbles": 35,
                "coins": 32,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58ab10",
            "id": "1488f225-46da-4573-89f4-967576dfaa7e",
            "chance": 100,
            "demand": "medium",
            "description": "Demonic Dogcat is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the N/A with a 100% chance.",
            "eggType": "N/A",
            "image": "/items/demonic-dogcat.png",
            "name": "Demonic Dogcat",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "demonic-dogcat",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ac0d",
                "petId": "1488f225-46da-4573-89f4-967576dfaa7e",
                "bubbles": 1300,
                "coins": 1800,
                "gems": 22,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aaf4",
            "id": "0da98b76-9f2f-4fb9-ba2c-93f15cf83cc1",
            "chance": 0.001,
            "demand": "low",
            "description": "Demonic Hydra is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the Nightmare Egg with a 0.001% chance.",
            "eggType": "Nightmare Egg",
            "image": "/items/demonic-hydra.png",
            "name": "Demonic Hydra",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-18T06:10:53.808Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "demonic-hydra",
            "value": "N/A",
            "variants": [
                "Normal",
                "Mythic",
                "ShinyMythic",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58abf1",
                "petId": "0da98b76-9f2f-4fb9-ba2c-93f15cf83cc1",
                "bubbles": 925,
                "coins": 1200,
                "gems": 15,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aac2",
            "id": "9d3ddca7-5a69-4da1-8bed-e34cbf0ebbaf",
            "chance": 30,
            "demand": "medium",
            "description": "Dinosaur is a Common pet in Bubble Gum Simulator Infinity. It can be hatched from the Spikey Egg with a 30% chance.",
            "eggType": "Spikey Egg",
            "image": "/items/dinosaur.png",
            "name": "Dinosaur",
            "owners": 0,
            "rarity": "Common",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "dinosaur",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58abbf",
                "petId": "9d3ddca7-5a69-4da1-8bed-e34cbf0ebbaf",
                "bubbles": 3,
                "coins": 2,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aaca",
            "id": "c89affb8-2588-4e53-a13e-6b4cc2f01d3d",
            "chance": 100,
            "demand": "medium",
            "description": "Discord Imp is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the N/A with a 100% chance.",
            "eggType": "N/A",
            "image": "/items/discord-imp.png",
            "name": "Discord Imp",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "discord-imp",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58abc7",
                "petId": "c89affb8-2588-4e53-a13e-6b4cc2f01d3d",
                "bubbles": 25,
                "coins": 20,
                "gems": 2,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa92",
            "id": "c4e29f35-f760-460e-8a66-222122f4018f",
            "chance": 40,
            "demand": "medium",
            "description": "Doggy is a Common pet in Bubble Gum Simulator Infinity. It can be hatched from the Common Egg with a 40% chance.",
            "eggType": "Common Egg",
            "image": "/items/doggy.png",
            "name": "Doggy",
            "owners": 0,
            "rarity": "Common",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "doggy",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ab8f",
                "petId": "c4e29f35-f760-460e-8a66-222122f4018f",
                "bubbles": 1,
                "coins": 1.1,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa86",
            "id": "a3e9304e-1ef8-4a7b-9fd9-249db46d8e4e",
            "chance": 100,
            "demand": "high",
            "description": "Dowodle is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the N/A with a 100% chance.",
            "eggType": "N/A",
            "image": "/items/dowodle.png",
            "name": "Dowodle",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "up",
            "status": "Limited",
            "updatedAt": "2025-04-15T22:56:04.801Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "dowodle",
            "value": 600,
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 600,
            "stats": {
                "_id": "67fc4656998e9806cb58ab83",
                "petId": "a3e9304e-1ef8-4a7b-9fd9-249db46d8e4e",
                "bubbles": 120,
                "coins": 135,
                "gems": 1.5,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aaee",
            "id": "98bcc0ba-33b0-469d-80be-581fd9689780",
            "chance": 12,
            "demand": "medium",
            "description": "Dragon is a Rare pet in Bubble Gum Simulator Infinity. It can be hatched from the Spikey Egg with a 12% chance.",
            "eggType": "Spikey Egg",
            "image": "/items/dragon.png",
            "name": "Dragon",
            "owners": 0,
            "rarity": "Rare",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "dragon",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58abeb",
                "petId": "98bcc0ba-33b0-469d-80be-581fd9689780",
                "bubbles": 12,
                "coins": 8,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "6802d61ceabfff64116d438b",
            "id": "dc1bfc6c-eaa5-4a7a-972d-3671253a03ae",
            "chance": 0.000001,
            "demand": "medium",
            "description": "Easter Basket is a Secret pet in Bubble Gum Simulator Infinity. It can be hatched from the Bunny Egg with a 0.000001% chance.",
            "eggType": "Bunny Egg",
            "image": "/items/easter-basket.png",
            "name": "Easter Basket",
            "owners": 0,
            "rarity": "Secret",
            "trend": "stable",
            "status": "Limited",
            "updatedAt": "2025-04-18T22:48:47.280Z",
            "releasedAt": "2025-04-18T21:00:00.000Z",
            "slug": "easter-basket",
            "value": "N/A",
            "variants": [
                "Normal",
                "Mythic",
                "ShinyMythic",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "6802d6c14654baa6902f69e0",
                "petId": "dc1bfc6c-eaa5-4a7a-972d-3671253a03ae",
                "__v": 0,
                "bubbles": 2900,
                "coins": 3500,
                "gems": 60,
                "worldCurrency": {}
            }
        },
        {
            "_id": "6802d61ceabfff64116d4395",
            "id": "69cfa9c9-a831-4110-a831-46e7d9707de7",
            "chance": 30,
            "demand": "medium",
            "description": "Egg Bunny is a Unique pet in Bubble Gum Simulator Infinity. It can be hatched from the Bunny Egg with a 30% chance.",
            "eggType": "Bunny Egg",
            "image": "/items/egg-bunny.png",
            "name": "Egg Bunny",
            "owners": 0,
            "rarity": "Unique",
            "trend": "stable",
            "status": "Limited",
            "updatedAt": "2025-04-18T22:48:47.280Z",
            "releasedAt": "2025-04-18T21:00:00.000Z",
            "slug": "egg-bunny",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "6802d6c14654baa6902f69ea",
                "petId": "69cfa9c9-a831-4110-a831-46e7d9707de7",
                "__v": 0,
                "bubbles": 88,
                "coins": 105,
                "gems": 1.8,
                "worldCurrency": {}
            }
        },
        {
            "_id": "67fc4654998e9806cb58ab24",
            "id": "aa229336-4c3e-499e-8ae0-b411d36d29e7",
            "chance": 0.1,
            "demand": "medium",
            "description": "Electra is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the Lunar Egg with a 0.1% chance.",
            "eggType": "Lunar Egg",
            "image": "/items/electra.png",
            "name": "Electra",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "electra",
            "value": "N/A",
            "variants": [
                "Normal",
                "Mythic",
                "ShinyMythic",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ac21",
                "petId": "aa229336-4c3e-499e-8ae0-b411d36d29e7",
                "bubbles": 295,
                "coins": 395,
                "gems": 4,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58ab2c",
            "id": "4d14f0b3-5c8a-4c8d-87dc-760a37d38756",
            "chance": 2.25,
            "demand": "medium",
            "description": "Emerald Bat is a Epic pet in Bubble Gum Simulator Infinity. It can be hatched from the Crystal Egg with a 2.25% chance.",
            "eggType": "Crystal Egg",
            "image": "/items/emerald-bat.png",
            "name": "Emerald Bat",
            "owners": 0,
            "rarity": "Epic",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "emerald-bat",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ac29",
                "petId": "4d14f0b3-5c8a-4c8d-87dc-760a37d38756",
                "bubbles": 50,
                "coins": 35,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58ab14",
            "id": "68287876-388f-428b-b410-ab361a0e93f0",
            "chance": 0.5,
            "demand": "medium",
            "description": "Emerald Golem is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the Spikey Egg with a 0.5% chance.",
            "eggType": "Spikey Egg",
            "image": "/items/emerald-golem.png",
            "name": "Emerald Golem",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "emerald-golem",
            "value": "N/A",
            "variants": [
                "Normal",
                "Mythic",
                "ShinyMythic",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ac11",
                "petId": "68287876-388f-428b-b410-ab361a0e93f0",
                "bubbles": 45,
                "coins": 25,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aac8",
            "id": "dd15f9f5-a88f-4850-b6b6-59b9ab616442",
            "chance": 90,
            "demand": "medium",
            "description": "Enlightened Kitty is a Rare pet in Bubble Gum Simulator Infinity. It can be hatched from the Season 1 Egg with a 90% chance.",
            "eggType": "Season 1 Egg",
            "image": "/items/enlightened-kitty.png",
            "name": "Enlightened Kitty",
            "owners": 0,
            "rarity": "Rare",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "enlightened-kitty",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58abc5",
                "petId": "dd15f9f5-a88f-4850-b6b6-59b9ab616442",
                "bubbles": 35,
                "coins": 15,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "6802d61ceabfff64116d437d",
            "id": "e0e00ba3-8964-4cb6-b875-8b25cc8c6497",
            "chance": 0.001,
            "demand": "medium",
            "description": "Ethereal Bunny is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the Bunny Egg with a 0.001% chance.",
            "eggType": "Bunny Egg",
            "image": "/items/ethereal-bunny.png",
            "name": "Ethereal Bunny",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "stable",
            "status": "Limited",
            "updatedAt": "2025-04-18T22:48:47.280Z",
            "releasedAt": "2025-04-18T21:00:00.000Z",
            "slug": "ethereal-bunny",
            "value": "N/A",
            "variants": [
                "Normal",
                "Mythic",
                "ShinyMythic",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "6802d6c14654baa6902f69d2",
                "petId": "e0e00ba3-8964-4cb6-b875-8b25cc8c6497",
                "__v": 0,
                "bubbles": 1075,
                "coins": 1400,
                "gems": 19,
                "worldCurrency": {}
            }
        },
        {
            "_id": "67fc4654998e9806cb58aac6",
            "id": "f614607d-fba6-4f1d-8631-7fa06a9f3ebc",
            "chance": 100,
            "demand": "low",
            "description": "Evil Shock is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the N/A with a 100% chance.",
            "eggType": "N/A",
            "image": "/items/evil-shock.png",
            "name": "Evil Shock",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "down",
            "status": "Permanent",
            "updatedAt": "2025-04-18T06:34:51.791Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "evil-shock",
            "value": 30,
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 30,
            "stats": {
                "_id": "67fc4656998e9806cb58abc3",
                "petId": "f614607d-fba6-4f1d-8631-7fa06a9f3ebc",
                "bubbles": 975,
                "coins": 1300,
                "gems": 15.5,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa3e",
            "id": "e64ede7b-36e4-42c4-868a-c621aec55588",
            "chance": 100,
            "demand": "medium",
            "description": "Flying Gem is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the N/A with a 100% chance.",
            "eggType": "N/A",
            "image": "/items/flying-gem.png",
            "name": "Flying Gem",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.941Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "flying-gem",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ab3b",
                "petId": "e64ede7b-36e4-42c4-868a-c621aec55588",
                "bubbles": 50,
                "coins": 35,
                "gems": 4.5,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58ab28",
            "id": "be38d4ae-3e1e-474d-b599-4e3f21ea5293",
            "chance": 0.1,
            "demand": "medium",
            "description": "Flying Pig is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the Crystal Egg with a 0.1% chance.",
            "eggType": "Crystal Egg",
            "image": "/items/flying-pig.png",
            "name": "Flying Pig",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "flying-pig",
            "value": "N/A",
            "variants": [
                "Normal",
                "Mythic",
                "ShinyMythic",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ac25",
                "petId": "be38d4ae-3e1e-474d-b599-4e3f21ea5293",
                "bubbles": 285,
                "coins": 310,
                "gems": 1.7,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aadc",
            "id": "a65d65d7-77e5-459d-9509-42ab4f10c804",
            "chance": 20,
            "demand": "medium",
            "description": "Fox is a Unique pet in Bubble Gum Simulator Infinity. It can be hatched from the Spotted Egg with a 20% chance.",
            "eggType": "Spotted Egg",
            "image": "/items/fox.png",
            "name": "Fox",
            "owners": 0,
            "rarity": "Unique",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "fox",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58abd9",
                "petId": "a65d65d7-77e5-459d-9509-42ab4f10c804",
                "bubbles": 3,
                "coins": 2.2,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "6802d61ceabfff64116d4397",
            "id": "8dacd060-bfc8-47b7-ae79-0da5bd28da51",
            "chance": 0.000002,
            "demand": "medium",
            "description": "Giant Chocolate Chicken is a Secret pet in Bubble Gum Simulator Infinity. It can be hatched from the Pastel Egg with a 0.000002% chance.",
            "eggType": "Pastel Egg",
            "image": "/items/giant-chocolate-chicken.png",
            "name": "Giant Chocolate Chicken",
            "owners": 0,
            "rarity": "Secret",
            "trend": "stable",
            "status": "Limited",
            "updatedAt": "2025-04-18T22:48:47.280Z",
            "releasedAt": "2025-04-18T21:00:00.000Z",
            "slug": "giant-chocolate-chicken",
            "value": "N/A",
            "variants": [
                "Normal",
                "Mythic",
                "ShinyMythic",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "6802d6c14654baa6902f69ec",
                "petId": "8dacd060-bfc8-47b7-ae79-0da5bd28da51",
                "__v": 0,
                "bubbles": 2225,
                "coins": 3100,
                "gems": 45,
                "worldCurrency": {}
            }
        },
        {
            "_id": "67fc4654998e9806cb58ab20",
            "id": "42768f56-3bb4-4bd2-a9d9-7a0e2adf434e",
            "chance": 30,
            "demand": "medium",
            "description": "Golem is a Common pet in Bubble Gum Simulator Infinity. It can be hatched from the Spikey Egg with a 30% chance.",
            "eggType": "Spikey Egg",
            "image": "/items/golem.png",
            "name": "Golem",
            "owners": 0,
            "rarity": "Common",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "golem",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ac1d",
                "petId": "42768f56-3bb4-4bd2-a9d9-7a0e2adf434e",
                "bubbles": 3,
                "coins": 4,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa68",
            "id": "ec3b7a26-b7ae-4701-a7a5-18a8ae1c6107",
            "chance": 2.25,
            "demand": "medium",
            "description": "Green Angel is a Epic pet in Bubble Gum Simulator Infinity. It can be hatched from the Rainbow Egg with a 2.25% chance.",
            "eggType": "Rainbow Egg",
            "image": "/items/green-angel.png",
            "name": "Green Angel",
            "owners": 0,
            "rarity": "Epic",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.941Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "green-angel",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ab65",
                "petId": "ec3b7a26-b7ae-4701-a7a5-18a8ae1c6107",
                "bubbles": 225,
                "coins": 285,
                "gems": 2,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aafa",
            "id": "622948a8-956b-4ca3-8ec0-9bea7d643c98",
            "chance": 0.004,
            "demand": "medium",
            "description": "Green Hydra is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the Nightmare Egg with a 0.004% chance.",
            "eggType": "Nightmare Egg",
            "image": "/items/green-hydra.png",
            "name": "Green Hydra",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "green-hydra",
            "value": "N/A",
            "variants": [
                "Normal",
                "Mythic",
                "ShinyMythic",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58abf7",
                "petId": "622948a8-956b-4ca3-8ec0-9bea7d643c98",
                "bubbles": 600,
                "coins": 710,
                "gems": 10,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa9e",
            "id": "d3453246-db21-475f-a1f5-e5d37a737db8",
            "chance": 0.025,
            "demand": "medium",
            "description": "Hacker Prism is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the N/A with a 0.025% chance.",
            "eggType": "N/A",
            "image": "/items/hacker-prism.png",
            "name": "Hacker Prism",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "down",
            "status": "Permanent",
            "updatedAt": "2025-04-16T19:06:46.303Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "hacker-prism",
            "value": 190,
            "variants": [
                "Normal",
                "Mythic",
                "ShinyMythic",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 190,
            "stats": {
                "_id": "67fc4656998e9806cb58ab9b",
                "petId": "d3453246-db21-475f-a1f5-e5d37a737db8",
                "bubbles": 1450,
                "coins": 1850,
                "gems": 22,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "6802d61ceabfff64116d4393",
            "id": "14e6816f-7a89-4949-8ef4-7616b0c4c64f",
            "chance": 2.25,
            "demand": "medium",
            "description": "Hatchling is a Epic pet in Bubble Gum Simulator Infinity. It can be hatched from the Pastel Egg with a 2.25% chance.",
            "eggType": "Pastel Egg",
            "image": "/items/hatchling.png",
            "name": "Hatchling",
            "owners": 0,
            "rarity": "Epic",
            "trend": "stable",
            "status": "Limited",
            "updatedAt": "2025-04-18T22:48:47.280Z",
            "releasedAt": "2025-04-18T21:00:00.000Z",
            "slug": "hatchling",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "6802d6c14654baa6902f69e8",
                "petId": "14e6816f-7a89-4949-8ef4-7616b0c4c64f",
                "__v": 0,
                "bubbles": 190,
                "coins": 265,
                "gems": 0,
                "worldCurrency": {}
            }
        },
        {
            "_id": "67fc4654998e9806cb58ab06",
            "id": "b4bb8603-dc4e-43af-95b2-3e7da3a75ee5",
            "chance": 2.25,
            "demand": "medium",
            "description": "Hell Bat is a Epic pet in Bubble Gum Simulator Infinity. It can be hatched from the Nightmare Egg with a 2.25% chance.",
            "eggType": "Nightmare Egg",
            "image": "/items/hell-bat.png",
            "name": "Hell Bat",
            "owners": 0,
            "rarity": "Epic",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "hell-bat",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ac03",
                "petId": "b4bb8603-dc4e-43af-95b2-3e7da3a75ee5",
                "bubbles": 185,
                "coins": 250,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aaa8",
            "id": "8fbbaddc-b684-4082-957e-ba3b8ddcb50b",
            "chance": 7,
            "demand": "medium",
            "description": "Hell Crawler is a Rare pet in Bubble Gum Simulator Infinity. It can be hatched from the Hell Egg with a 7% chance.",
            "eggType": "Hell Egg",
            "image": "/items/hell-crawler.png",
            "name": "Hell Crawler",
            "owners": 0,
            "rarity": "Rare",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "hell-crawler",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58aba5",
                "petId": "8fbbaddc-b684-4082-957e-ba3b8ddcb50b",
                "bubbles": 75,
                "coins": 75,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58ab12",
            "id": "9816f779-6490-4db8-bdd6-0fc72835b54e",
            "chance": 29.9,
            "demand": "medium",
            "description": "Hell Dragon is a Unique pet in Bubble Gum Simulator Infinity. It can be hatched from the Hell Egg with a 29.9% chance.",
            "eggType": "Hell Egg",
            "image": "/items/hell-dragon.png",
            "name": "Hell Dragon",
            "owners": 0,
            "rarity": "Unique",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "hell-dragon",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ac0f",
                "petId": "9816f779-6490-4db8-bdd6-0fc72835b54e",
                "bubbles": 45,
                "coins": 45,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa8c",
            "id": "8b2bfa4f-b523-4167-8731-9c875a5bfd7a",
            "chance": 60,
            "demand": "medium",
            "description": "Hell Piggy is a Common pet in Bubble Gum Simulator Infinity. It can be hatched from the Hell Egg with a 60% chance.",
            "eggType": "Hell Egg",
            "image": "/items/hell-piggy.png",
            "name": "Hell Piggy",
            "owners": 0,
            "rarity": "Common",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "hell-piggy",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ab89",
                "petId": "8b2bfa4f-b523-4167-8731-9c875a5bfd7a",
                "bubbles": 24,
                "coins": 20,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58ab02",
            "id": "3ba14a48-4dea-4641-959c-4dcd72ae9c3d",
            "chance": 0.001,
            "demand": "low",
            "description": "Hexarium is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the Rainbow Egg with a 0.001% chance.",
            "eggType": "Rainbow Egg",
            "image": "/items/hexarium.png",
            "name": "Hexarium",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "down",
            "status": "Permanent",
            "updatedAt": "2025-04-18T06:14:06.276Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "hexarium",
            "value": 10,
            "variants": [
                "Normal",
                "Mythic",
                "ShinyMythic",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 10,
            "stats": {
                "_id": "67fc4656998e9806cb58abff",
                "petId": "3ba14a48-4dea-4641-959c-4dcd72ae9c3d",
                "bubbles": 1025,
                "coins": 1350,
                "gems": 16.5,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aac0",
            "id": "b9e7a551-9deb-44f0-b958-ea32133bc288",
            "chance": 100,
            "demand": "low",
            "description": "Holy Shock is a Legendary pet in Bubble Gum Simulator Infinity. It can be hatched from the N/A with a 100% chance.",
            "eggType": "N/A",
            "image": "/items/holy-shock.png",
            "name": "Holy Shock",
            "owners": 0,
            "rarity": "Legendary",
            "trend": "down",
            "status": "Permanent",
            "updatedAt": "2025-04-18T06:41:35.923Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "holy-shock",
            "value": 35,
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 35,
            "stats": {
                "_id": "67fc4656998e9806cb58abbd",
                "petId": "b9e7a551-9deb-44f0-b958-ea32133bc288",
                "bubbles": 975,
                "coins": 1300,
                "gems": 15.5,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa7a",
            "id": "eb5854e6-ef50-4806-8aa9-88e5e7cb0845",
            "chance": 8,
            "demand": "medium",
            "description": "Ice Deer is a Rare pet in Bubble Gum Simulator Infinity. It can be hatched from the Iceshard Egg with a 8% chance.",
            "eggType": "Iceshard Egg",
            "image": "/items/ice-deer.png",
            "name": "Ice Deer",
            "owners": 0,
            "rarity": "Rare",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.942Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "ice-deer",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ab77",
                "petId": "eb5854e6-ef50-4806-8aa9-88e5e7cb0845",
                "bubbles": 11,
                "coins": 7,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        },
        {
            "_id": "67fc4654998e9806cb58aa64",
            "id": "83fde8e6-f69b-45d5-9f6f-a219514955cb",
            "chance": 3,
            "demand": "medium",
            "description": "Ice Dragon is a Epic pet in Bubble Gum Simulator Infinity. It can be hatched from the Iceshard Egg with a 3% chance.",
            "eggType": "Iceshard Egg",
            "image": "/items/ice-dragon.png",
            "name": "Ice Dragon",
            "owners": 0,
            "rarity": "Epic",
            "trend": "stable",
            "status": "Permanent",
            "updatedAt": "2025-04-13T23:18:44.941Z",
            "releasedAt": "2025-04-11T20:00:00.000Z",
            "slug": "ice-dragon",
            "value": "N/A",
            "variants": [
                "Normal",
                "Shiny"
            ],
            "variant": "Normal",
            "__v": 0,
            "numericValue": 0,
            "stats": {
                "_id": "67fc4656998e9806cb58ab61",
                "petId": "83fde8e6-f69b-45d5-9f6f-a219514955cb",
                "bubbles": 15,
                "coins": 10,
                "gems": 0,
                "worldCurrency": {},
                "__v": 0
            }
        }
    ],
    "pagination": {
        "total": 290,
        "pages": 6,
        "current": 1
    }
}
